// Generated by scripts/multiplayer/prepare-collision.mjs; regenerate after world or lock changes.
export const COLLISION_RELEASE = Object.freeze({
  schema: 1,
  protocol: "ashen-presence-v1",
  collisionHash:
    "3623939d1d15add04b47ed7ab24cdbeb8d864ee032c29c74407657ad90fd0b21",
  sourceHash:
    "2e04004b977a0365ea6f398a7e0d2250987ef4de0aefe2acf9219303e1ec4baf",
  file: "collision-3623939d1d15add04b47ed7ab24cdbeb8d864ee032c29c74407657ad90fd0b21.json",
  bytes: 199029,
  data: {
    file: "collision-444fed2cecb92463135accfe05a7a8f438b7e4e8358ed1b9afe35e27c7a835b7.bin",
    sha256: "444fed2cecb92463135accfe05a7a8f438b7e4e8358ed1b9afe35e27c7a835b7",
    bytes: 17518656,
  },
});
