import {chromium} from 'playwright';import fs from 'node:fs/promises';
const graveweaver=process.argv.includes('--graveweaver'),mixed=process.argv.includes('--mixed'),equipment=graveweaver||mixed||process.argv.includes('--equipment');
const browser=await chromium.connectOverCDP('http://127.0.0.1:9337');const page=browser.contexts()[0].pages().find(p=>p.url().includes('ashen-reach.html'));
try{
 await page.bringToFront();if(await page.evaluate(()=>ASHEN.armory.isOpen))await page.keyboard.press('Escape');await page.evaluate(preset=>{ASHEN.setView('play');if(preset)ASHEN.equipment.equipPreset(preset);},graveweaver?'graveweaver':mixed?'pilgrim':equipment?'wayfarer':null);await page.waitForTimeout(1800);
 const sample=()=>page.evaluate(()=>new Promise(resolve=>{const values=[];let last,draws=0;const started=performance.now();function tick(time){if(last!==undefined)values.push(time-last);last=time;draws=Math.max(draws,ASHEN.engine.drawCallCount);if(time-started<5500){requestAnimationFrame(tick);return;}const sorted=[...values].sort((a,b)=>a-b),mean=values.reduce((a,b)=>a+b,0)/values.length;resolve({frames:values.length,seconds:(time-started)/1000,meanMs:mean,fps:1000/mean,p95Ms:sorted[Math.floor(sorted.length*.95)],worstMs:sorted.at(-1),over16ms:values.filter(t=>t>16.67).length,maxDrawCalls:draws,resolution:ASHEN.metrics.summary().resolution});}requestAnimationFrame(tick);}));
 const play=await sample();await page.keyboard.press('KeyC');await page.locator('[data-motion]').selectOption('run');await page.locator('[data-light]').check();await page.waitForTimeout(1200);const armory=await sample();
 const result={play,armory,loadout:await page.evaluate(()=>ASHEN.equipment.getState()),note:'Foreground owned Chrome, no recording, one character. Armory running source clip with inspection fill light. Short local samples; not crowd/native-resolution proof.'};await fs.writeFile(`ve-capture/ashen-reach/${graveweaver?'graveweaver':mixed?'mixed-equipment':equipment?'equipment':'armory'}/performance.json`,JSON.stringify(result,null,2));console.log(result);
}finally{await browser.close();}
