import {chromium} from 'playwright';
import fs from 'node:fs/promises';
const b=await chromium.connectOverCDP('http://127.0.0.1:9337');
const p=b.contexts()[0].pages().find(p=>p.url().includes('ashen-reach'));
await p.bringToFront();await p.waitForFunction(()=>window.ASHEN?.ready,null,{timeout:120000});
const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await p.evaluate(()=>{ASHEN.reset();ASHEN.setView('play');});
await p.waitForTimeout(1000);
const start=await p.evaluate(()=>ASHEN.player.getDebugState());
await p.keyboard.down('KeyW');await p.waitForTimeout(800);await p.keyboard.up('KeyW');await p.waitForTimeout(300);
const moved=await p.evaluate(()=>ASHEN.player.getDebugState());
await p.keyboard.down('KeyD');await p.waitForTimeout(300);await p.keyboard.up('KeyD');await p.waitForTimeout(100);
const turned=await p.evaluate(()=>ASHEN.player.getDebugState());
await p.keyboard.down('Space');await p.waitForTimeout(130);await p.keyboard.up('Space');
const airborne=await p.evaluate(()=>ASHEN.player.getDebugState());
await p.screenshot({path:'ve-capture/ashen-reach/jump.png'});
await p.waitForTimeout(1600);
const landed=await p.evaluate(()=>ASHEN.player.getDebugState());
await p.evaluate(()=>{ASHEN.reset();ASHEN.setView('play');});await p.waitForTimeout(700);
await p.screenshot({path:'ve-capture/ashen-reach/third-person.png'});
await p.waitForTimeout(11000);
const metrics=await p.evaluate(()=>ASHEN.metrics.summary());
const result={errors,start,moved,turned,airborne,landed,metrics,checks:{walk:Math.hypot(moved.position.x-start.position.x,moved.position.z-start.position.z)>2,turn:Math.abs(turned.facing-moved.facing)>.3,jump:airborne.jumps>turned.jumps&&!airborne.grounded,land:landed.grounded&&landed.landings>turned.landings,havok:start.usingPhysics,cleanConsole:!errors.length}};
await fs.writeFile('ve-capture/ashen-reach/playtest.json',JSON.stringify(result,null,2));console.log(JSON.stringify({metrics,checks:result.checks,errors},null,2));
await p.evaluate(()=>ASHEN.setView('reference'));await p.waitForTimeout(1000);await p.screenshot({path:'ve-capture/ashen-reach/reference.png'});
await b.close();if(Object.values(result.checks).some(x=>!x))process.exitCode=1;
